version: "3"
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: 'votofacil'
      MYSQL_USER: 'votofacil'
      MYSQL_PASSWORD: 'votosecreto'
      MYSQL_ROOT_PASSWORD: 'votosecreto'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.docker/mysql:/var/lib/mysql'
  app:
    image: fsantos/votofacil:latest
    ports:
      - 8080:8080
    links:
      - mysqldb
      - kafka
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
